//! Regression pinning — emit a proptest file seeding the shrunk
//! counterexamples of late-killed mutants (v2.0 §4.2). The emitted file is
//! generated SOURCE FOR THE TARGET CODEBASE (which depends on proptest);
//! this crate only renders text.

use harness::CounterExample;

pub fn emit_pinned_suite(fn_name: &str, phi_src: &str, pinned: &[CounterExample]) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by dge gentest — pinned regression suite.\n");
    out.push_str("// Each #[test] is a shrunk (T3-minimal) counterexample; the proptest\n");
    out.push_str("// block re-samples mu' around them on every run.\n");
    out.push_str("use proptest::prelude::*;\n\n");
    out.push_str(&format!("fn phi(env: &[f64], out: f64) -> bool {{ {phi_src} }}\n\n"));

    for (i, ce) in pinned.iter().enumerate() {
        out.push_str(&format!(
            "#[test]\nfn pinned_ce_{i}() {{\n    let env = vec!{:?};\n    \
             assert!(phi(&env, {fn_name}(&env)), \"pinned counterexample regressed\");\n}}\n\n",
            ce.minimal_env
        ));
    }

    out.push_str(&format!(
"proptest! {{
    #[test]
    fn phi_holds_under_mu_prime(env in proptest::collection::vec(any::<f64>(), 1..8)) {{
        // NOTE: replace any::<f64>() with the mu'-mixture strategy from the
        // dge harness adapter for the T4-quantified guarantee.
        prop_assert!(phi(&env, {fn_name}(&env)));
    }}
}}\n"));
    out
}

/// Golden regression suite: each case pins the CURRENT output as expected
/// (the automatable φ when no spec predicate is supplied — `dge gentest`).
pub fn emit_golden_suite(fn_name: &str, cases: &[(Vec<f64>, f64)]) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by dge gentest — golden regression suite.\n");
    out.push_str("// Each env was selected because it kills >=1 mutant of the\n");
    out.push_str("// function under test; expected values are the current outputs.\n\n");
    for (i, (env, expected)) in cases.iter().enumerate() {
        out.push_str(&format!(
            "#[test]\nfn golden_{i}() {{\n    let env = vec!{env:?};\n    \
             assert_eq!({fn_name}(&env).to_bits(), {:#018x}u64, \"golden output changed\");\n}}\n\n",
            expected.to_bits()
        ));
    }
    out
}
