// AUTO-GENERATED by dge emit — do not hand-edit.
// Re-run the pipeline instead; hand edits VOID the certificate.
/// CERTIFIED: PROVED semantics-preserving; 2 rule(s) [0 SMT artifact(s)]
/// rules applied: add-comm, mul-comm
/// env: x86_64 fma=true avx=true libm=behavioral:da9da77b07139d63
#[allow(unused_parens, clippy::all)]
pub fn poly_dge(v0: f64) -> f64 {
    ((((v0 * (v0 * (3.0_f64 * v0))) + (v0 * (v0 * 5.0_f64))) + (v0 * 2.0_f64)) + 7.0_f64)
}
